[tools]
usage = "latest" # for mise completions
erlang = "latest"
elixir = "latest"
node = "latest"
rust = "latest"
zig = "latest"
zls = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:cli/cli" = "latest" # github cli
"aqua:getsops/sops" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:starship/starship" = "latest"
"aqua:superfly/flyctl" = "latest"
"npm:@google/gemini-cli" = "latest"
"ubi:charmbracelet/crush" = "latest"
"ubi:openai/codex" = "latest"
"ubi:sst/opencode" = "latest"

[settings]
experimental = true
